// build.rs
//
// Auto-discovers language backends in src/languages/ so adding a new language
// is just "drop a file in there" — no manual mod declarations or registry edits.
//
// Every *.rs file in src/languages/ (except mod.rs) is assumed to be a language
// module exposing `pub fn config() -> CompilerConfig`. We generate a small Rust
// file into OUT_DIR declaring each as a module and collecting their configs into
// `all_languages()`, which languages/mod.rs includes verbatim.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let languages_dir = Path::new("src/languages");
    println!("cargo:rerun-if-changed={}", languages_dir.display());

    let mut modules = Vec::new();
    for entry in fs::read_dir(languages_dir).expect("failed to read src/languages") {
        let entry = entry.expect("failed to read dir entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
        if stem == "mod" {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        modules.push(stem);
    }
    modules.sort();

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n\n");
    for m in &modules {
        // #[path] points back at the real source file, since `include!` resolves
        // module paths relative to OUT_DIR rather than src/languages/.
        out.push_str(&format!(
            "#[path = \"{manifest_dir}/src/languages/{m}.rs\"]\npub mod {m};\n",
            manifest_dir = manifest_dir,
            m = m
        ));
    }
    out.push_str("\npub fn all_languages() -> Vec<CompilerConfig> {\n    vec![\n");
    for m in &modules {
        out.push_str(&format!("        {}::config(),\n", m));
    }
    out.push_str("    ]\n}\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("language_registry.rs");
    fs::write(&dest, out).expect("failed to write generated language registry");
}
